{% set name = "HMMRATAC" %}
{% set version = "1.2.5" %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  url: https://github.com/LiuLabUB/{{ name }}/releases/download/{{ version }}/{{ name }}_V{{ version }}_exe.jar
  sha256: 

build:
  number: 0
  noarch: generic

requirements:
  host:
    - openjdk
  run:
    - openjdk

test:
  commands:
    - HMMERATAC --help

about:
  home: https://github.com/LiuLabUB/HMMRATAC
  license: Unknown
  summary: Peak caller for ATAC-seq data

extra:
  identifiers:
    - doi:10.1093/nar/gkz533
