{% set name = "riboSeed" %}
{% set version = "0.4.78" %}
{% set hash_type = "sha256" %}
{% set hash_value = "2742614fca5f8ef6a65ce9f755604672a6f7b5225f4ed5a3f57d5e6debfe385b" %}


package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: generic
  entry_points:
    - ribo = riboSeed.ribo:main
  skip: True  # [py2k]
  skip: True  # [py34]
  skip: True  # [py36]
  skip: True  # [py37]
requirements:
  host:
    - python
    - setuptools
    - biopython
    - pysam
    - jenkspy
    - pyaml
    - matplotlib
    - pandas
    - coverage
    - nose
    - networkx
    - bcbiogff
  run:
    # python reqs
    - biopython
    - jenkspy
    - pyaml
    - pysam
    - matplotlib
    - pandas
    - coverage
    - nose
    - networkx
    - bcbiogff
    # sys reqs
    - barrnap
    - mafft
    - prank
    - blast
    - spades ==3.9.0
    - bwa
    - samtools
    - bcftools
    - skesa
    #  this was broken, but should be resolved
    #  but quast is currently not being conda built for python 3 because some tests fail :(
    - quast >=4.6.3

test:
  imports:
    - riboSeed
  commands:
    - ribo

    - ribo scan -h
    - ribo select -h
    - ribo stack -h
    # the following tests are excluded until issue with mpl/Xserver gets sorted out, sorry!
    # - ribo run -h
    # - ribo seed -h
    # - ribo snag -h
    # - ribo sketch -h
    # - $PYTHON -m unittest tests.test_conda

about:
  home: https://github.com/nickp60/riboSeed
  license: MIT License
  license_family: MIT
  license_file: 'LICENSE'
  summary: 'riboSeed: assemble across rDNA regions'
  description: "Genome assembly polisher to bridge rDNA gaps"
  dev_url: 'https://github.com/nickp60/riboSeed'

extra:
  recipe-maintainers:
    - nickp60
