{% set name = "riboSeed" %}
{% set version = "0.4.84" %}
{% set hash_type = "sha256" %}
{% set hash_value = "b48a5e49211509710c3fab0d5c0449fdcf57b1ea117c707897c8934d1b0d8a38" %}


package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: generic
  entry_points:
    - ribo = riboSeed.ribo:main

requirements:
  host:
    - python 3.5.*
    - setuptools
    - biopython
    - pysam
    - jenkspy
    - pyaml
    - matplotlib
    - pandas
    - coverage
    - nose
    - networkx
    - bcbiogff
  run:
    - python 3.5.*
    # python reqs
    - biopython
    - jenkspy
    - pyaml
    - pysam
    - matplotlib
    - pandas
    - coverage
    - nose
    - networkx
    - bcbiogff
    # sys reqs
    - barrnap
    - mafft
    - prank
    - blast
    #- spades ==3.9.0
    - bwa
    - samtools
    - bcftools
    - skesa
    - quast >=4.6.3

test:
  imports:
    - riboSeed
  commands:
    - ribo
    - ribo scan -h
    - ribo select -h
    - ribo stack -h
    - ribo run -h
    - ribo seed -h
    - ribo snag -h
    - ribo sketch -h
    - $PYTHON -m unittest tests.test_conda
    - spades.py -v
    # run this for local builds, but dont waste the bioconda resources
    # this takes about 5 minutes to run by itself
    # - ribo run -r $PREFIX/lib/python3.5/site-packages/riboSeed/integration_data/concatenated_seq.fasta -F $PREFIX/lib/python3.5/site-packages/riboSeed/integration_data/test_reads1.fq -R $PREFIX/lib/python3.5/site-packages/riboSeed/integration_data/test_reads2.fq -o /tmp/riboseed/ --serialize --subassembler skesa -v 1
    # - ribo try
about:
  home: https://github.com/nickp60/riboSeed
  license: MIT License
  license_family: MIT
  license_file: 'LICENSE'
  summary: 'riboSeed: assemble across rDNA regions'
  description: "Genome assembly polisher to bridge rDNA gaps"
  dev_url: 'https://github.com/nickp60/riboSeed'

extra:
  recipe-maintainers:
    - nickp60
