package:
  name: spades
  version: '3.9.1'

source:
  url: http://cab.spbu.ru/files/release3.9.1/SPAdes-3.9.1.tar.gz
  sha256: da8e923fb1d5c1508b11a2928a8ca3efd8bf22a723d257f0e511c033f74022d8

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - libbz2
  run:
    - zlib
    - libbz2
    - python

test:
  commands:
    - spades.py --test && rm -rf spades_test

about:
  home: http://bioinf.spbau.ru/en/spades
  license: GPLv2
  license_file: LICENSE
  summary: SPAdes (St. Petersburg genome assembler) is intended for both standard isolates and single-cell MDA bacteria assemblies.

extra:
  identifiers:
    - biotools:Spades
    - doi:10.1089/cmb.2012.0021
