{% set name = "hca-matrix-downloader" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

source:
  url: https://github.com/ebi-gene-expression-group/hca-matrix-downloader/archive/v{{ version }}.tar.gz
  sha256: d7805b5c05cc55ee15a35451316ef1c0fca0908ccf8d9a3c759967e7ffcb6cc8

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - setuptools
    - requests

test:
  commands:
    - hca-matrix-downloader -h
    - hca-mtx-to-10x

about:
  home: https://github.com/ebi-gene-expression-group/hca-matrix-downloader
  license: MIT
  summary: Python client for the HCA DCP matrix service
