{% set name = "unitig-caller" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/johnlees/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: b1d2cd8b579d3b56192e673d6f69bbec3e31e3ebe5744c04ae864aee99cab0b5

build:
  number: 0
  skip: True  # [osx or py27]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - unitig-caller = unitig_caller.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - pybind11
  run:
    - python
    - mantis
    - squeakr >=0.6

test:
  commands:
    - unitig-caller --version

about:
   home: https://github.com/johnlees/unitig-caller
   license: Apache-2.0
   license_family: APACHE
   license_file: LICENSE
   summary: Determines presence/absence of sequence elements in bacterial sequence data.
