{% set name = "purple-bio" %}
{% set version = "0.4.2.4" %}
{% set sha256 = "b86cffc173c96c3a7cd304c41665ae0bae2488f74224f08e2004b28da5bd924c" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: 
    - https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    - https://files.pythonhosted.org/packages/1a/ef/00e7a8269ff28ade3f179088185b8cd1663e4eda0a05a0397af24320d8e3/purple_bio-0.4.2.4.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - biopython
    - python >=3
    - tqdm
    - pyyaml


test:
  imports:
    - purple

about:
  home: https://gitlab.com/HartkopfF/Purple
  license: GNU Lesser General Public v3 or later (LGPLv3+)
  license_family: LGPL 
  summary: Picking Unique Relevant Peptides for viraL Experiments

extra:
  recipe-maintainers:
    - TheBready
